version: '3.7'

services:
  core:
    container_name: core
    build: "./core"
    command: sh -c ". ./start.sh"
    volumes:
      - ./core:/api
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: "./frontend"
    ports:
      - "3000:3000"
