# Generated by Django 4.2.2 on 2023-06-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
