# Generated by Django 4.2.2 on 2023-06-18 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_establishment_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('cod_establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13)),
                ('email_address', models.EmailField(max_length=254)),
                ('instagram', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=13)),
                ('cod_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
