# Generated by Django 4.2.2 on 2023-06-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='register',
            new_name='id',
        ),
    ]
